services:
  proxy:
    image: ghcr.io/ilyasmurov/proxyness:latest
    container_name: proxyness
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    volumes:
      - proxy-data:/data
    command: ["-addr", ":443", "-db", "/data/data.db", "-cert", "/data/cert.pem", "-keyfile", "/data/key.pem"]

  config:
    image: ghcr.io/ilyasmurov/proxyness-config:latest
    container_name: proxyness-config
    restart: unless-stopped
    network_mode: host
    volumes:
      - config-data:/data
    command: ["-addr", ":8443", "-db", "/data/config.db", "-admin-user", "${ADMIN_USER}", "-admin-pass", "${ADMIN_PASSWORD}", "-proxy", "https://127.0.0.1:443"]

  landing:
    image: ghcr.io/ilyasmurov/proxyness-landing:latest
    container_name: proxyness-landing
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  proxy-data:
  config-data:
