-- Proxyness Postgres schema. Mirrors the SQLite schema in server/internal/db/db.go.
-- Booleans are real BOOL; timestamps are TIMESTAMPTZ; integer PKs use identity columns
-- so the migration tool can insert explicit IDs and keep FKs intact.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    key             TEXT UNIQUE NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    client_version  TEXT NOT NULL DEFAULT '',
    machine_id      TEXT NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS traffic_stats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   BIGINT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    hour        TIMESTAMPTZ NOT NULL,
    bytes_in    BIGINT NOT NULL DEFAULT 0,
    bytes_out   BIGINT NOT NULL DEFAULT 0,
    connections BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_traffic_device_hour ON traffic_stats(device_id, hour);

CREATE TABLE IF NOT EXISTS changelog (
    id          TEXT PRIMARY KEY,
    title       TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    type        TEXT NOT NULL DEFAULT 'feature',
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level       TEXT NOT NULL DEFAULT 'info',
    message     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON logs(created_at);

CREATE TABLE IF NOT EXISTS sites (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                TEXT UNIQUE NOT NULL,
    label               TEXT NOT NULL,
    primary_domain      TEXT UNIQUE NOT NULL,
    approved            BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS site_domains (
    site_id     BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    domain      TEXT NOT NULL,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (site_id, domain)
);
CREATE INDEX IF NOT EXISTS idx_site_domains_domain ON site_domains(domain);

CREATE TABLE IF NOT EXISTS site_ips (
    site_id  BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    cidr     TEXT NOT NULL,
    PRIMARY KEY (site_id, cidr)
);

CREATE TABLE IF NOT EXISTS user_sites (
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    site_id     BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at  BIGINT NOT NULL,
    PRIMARY KEY (user_id, site_id)
);

COMMIT;
